/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include<stdint.h>
#define PERIPH_BASE        (0x40000000UL)
/*!< Peripheral memory map */
#define AHBPERIPH_BASE     (PERIPH_BASE + 0x00020000UL)
#define APB2PERIPH_BASE    (PERIPH_BASE + 0x00010000UL)
#define GPIOC_BASE         (APB2PERIPH_BASE + 0x00001000UL)
#define RCC_BASE           (AHBPERIPH_BASE + 0x00001000UL)

/******************  Bit definition for RCC_APB2ENR register  *****************/
// #define RCC_APB2ENR_IOPCEN_Pos   (4U)
// #define RCC_APB2ENR_IOPCEN_Msk   (0x1UL << RCC_APB2ENR_IOPCEN_Pos)  /*!< 0x00000010 */
// #define RCC_APB2ENR_IOPCEN       RCC_APB2ENR_IOPCEN_Msk            /*!< I/O port C clock enable */

// #define APB2EN_R_OFFSET          (0x18UL)
// #define RCC_APB2EN_R             (*(volatile unsigned int *)(RCC_BASE + APB2EN_R_OFFSET))

// #define CRH_R_OFFSET             (0x04UL)
// #define GPIOC_CRH_R              (*(volatile unsigned int *)(GPIOC_BASE + CRH_R_OFFSET))

// #define BSRR_R_OFFSET            (0x10UL)
// #define GPIOC_BSRR_R             (*(volatile unsigned int *)(GPIOC_BASE + BSRR_R_OFFSET))

#define GPIOCEN                  (1UL << 4U)
#define PIN13                    (13U)
#define LED_PIN                  (1UL << PIN13)
#define __IO volatile

/** 
  * @brief Reset and Clock Control
  */

typedef struct
{
  __IO uint32_t CR;
  __IO uint32_t CFGR;
  __IO uint32_t CIR;
  __IO uint32_t APB2RSTR;
  __IO uint32_t APB1RSTR;
  __IO uint32_t AHBENR;
  __IO uint32_t APB2ENR;
  __IO uint32_t APB1ENR;
  __IO uint32_t BDCR;
  __IO uint32_t CSR;


} RCC_TypeDef;

typedef struct
{
  __IO uint32_t CRL;
  __IO uint32_t CRH;
  __IO uint32_t IDR;
  __IO uint32_t ODR;
  __IO uint32_t BSRR;
  __IO uint32_t BRR;
  __IO uint32_t LCKR;
} GPIO_TypeDef;

#define RCC             ((RCC_TypeDef*)RCC_BASE)
#define GPIOC           ((GPIO_TypeDef*)GPIOC_BASE)



/* Main function */
int main() {
    // 1. ENABLE CLOCK ACCESS TO GPIOC
    //RCC_APB2EN_R |= GPIOCEN;
    RCC->APB2ENR |= GPIOCEN;

    // 2. SET GPIOC PIN 13 AS OUTPUT (CRH: for pins 8-15)
    // GPIOC_CRH_R &= ~(0xF << (4 * (PIN13 - 8)));  // Clear previous setting (each pin has 4 bits)
    // GPIOC_CRH_R |= (0x1 << (4 * (PIN13 - 8)));   // Set mode to output 10 MHz push-pull
    GPIOC->CRH &= ~(0xF << (4 * (PIN13 - 8)));
    GPIOC->CRH |= (0x1 << (4 * (PIN13 - 8))); 
    while (1) {
        // 3. TOGGLE GPIOC PIN 13
        GPIOC->BSRR = (LED_PIN << 16);
       // GPIOC_BSRR_R = (LED_PIN << 16);  // Reset pin 13
        for (volatile int i = 0; i < 1000000; ++i);  // Delay
        GPIOC->BSRR = LED_PIN;
       // GPIOC_BSRR_R = LED_PIN;  // Set pin 13
        for (volatile int i = 0; i < 1000000; ++i);  // Delay
    }

    return 0;
}
